#!/usr/bin/env python3
"""
gen_disasm_seeds.py — extract every static JSR/BSR target from the L1
fixture and emit them as a TOML discovery file's [functions].extra array.

Reads:   segagenesisrecomp/tests/fixtures/sonic1/l1/instructions.txt
Writes:  segagenesisrecomp/sonicthehedgehog/sonic1.disasm_seeds.toml

Each row in the fixture describes one 68K instruction. Wherever the
disasm calls JSR/BSR with a static target (BSR.S/W/L, JSR (xxx).w,
JSR (xxx).l, JSR d16(PC)), the target address is — by definition — a
callable subroutine entry the recompiler must translate. Seeding
function_finder with these entries restores faithfulness for code
the disasm reaches but our static call-graph walk misses (typically
"abandoned unused" subroutines whose callers themselves have no
upstream caller).

Bcc / DBcc / BRA targets are deliberately NOT included — those are
interior branch labels, not subroutine entries. Treating them as
function entries would split parent functions and break control
flow (the bug the now-removed auto-merge feature tried to paper over).
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

SUBMODULE_ROOT = Path(__file__).resolve().parents[2]
L1_FIXTURE     = SUBMODULE_ROOT / "tests" / "fixtures" / "sonic1" / "l1" / "instructions.txt"
OUT_PATH       = SUBMODULE_ROOT / "sonicthehedgehog" / "sonic1.disasm_seeds.toml"
HEADER_DEFAULT = (
    "# sonic1.disasm_seeds.toml — auto-generated by tests/tools/gen_disasm_seeds.py.\n"
    "# Every static JSR/BSR target from the s1disasm REV00 listing.\n"
    "# Reference from game.toml:\n"
    "#   [game]\n"
    "#   discovery_files = [\"sonic1.disasm_seeds.toml\"]\n"
    "\n"
)

ROW_RE = re.compile(r"^([0-9a-fA-F]+)\s+([0-9a-fA-F]+)\t([^\t]+)\t")

def decode_target(addr: int, b: bytes) -> int | None:
    if len(b) < 2:
        return None
    op = (b[0] << 8) | b[1]
    # BSR family: 0x61xx
    if (op & 0xFF00) == 0x6100:
        d8 = op & 0xFF
        if d8 == 0:
            if len(b) < 4: return None
            d = (b[2] << 8) | b[3]
            if d & 0x8000: d -= 0x10000
            return (addr + 2 + d) & 0xFFFFFF
        elif d8 == 0xFF:
            if len(b) < 6: return None
            d = (b[2] << 24) | (b[3] << 16) | (b[4] << 8) | b[5]
            if d & 0x80000000: d -= 0x100000000
            return (addr + 2 + d) & 0xFFFFFF
        else:
            d = d8
            if d & 0x80: d -= 0x100
            return (addr + 2 + d) & 0xFFFFFF
    # JSR (xxx).l = 0x4EB9 + 4-byte abs
    if op == 0x4EB9 and len(b) >= 6:
        return ((b[2] << 24) | (b[3] << 16) | (b[4] << 8) | b[5]) & 0xFFFFFF
    # JSR (xxx).w = 0x4EB8 + 2-byte signed-extended
    if op == 0x4EB8 and len(b) >= 4:
        t = (b[2] << 8) | b[3]
        if t & 0x8000: t -= 0x10000
        return t & 0xFFFFFF
    # JSR d16(PC) = 0x4EBA + 2-byte signed displacement
    if op == 0x4EBA and len(b) >= 4:
        d = (b[2] << 8) | b[3]
        if d & 0x8000: d -= 0x10000
        return (addr + 2 + d) & 0xFFFFFF
    return None

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--instructions", type=Path, default=L1_FIXTURE,
                    help="L1 instructions.txt fixture (from gen_l1_fixtures.py)")
    ap.add_argument("-o", "--output", type=Path, default=OUT_PATH,
                    help="output .disasm_seeds.txt path")
    ap.add_argument("--header", type=str, default=None,
                    help="override the file's header comment")
    ap.add_argument("--rom-max", type=lambda s: int(s, 0), default=0x400000,
                    help="reject targets >= this address (default 0x400000)")
    args = ap.parse_args()

    if not args.instructions.exists():
        print(f"L1 fixture missing: {args.instructions}", file=sys.stderr)
        print("Run gen_l1_fixtures.py first.", file=sys.stderr)
        return 2

    targets: set[int] = set()
    for line in args.instructions.read_text(encoding="utf-8").splitlines():
        m = ROW_RE.match(line)
        if not m: continue
        mn = m.group(3).lower()
        if not (mn.startswith("jsr") or mn.startswith("bsr")):
            continue
        addr = int(m.group(1), 16)
        b    = bytes.fromhex(m.group(2))
        t = decode_target(addr, b)
        if t is None:
            continue
        # Sanity: must be even and within ROM (Genesis cart limit).
        if (t & 1) or t >= args.rom_max:
            continue
        targets.add(t)

    args.output.parent.mkdir(parents=True, exist_ok=True)
    header = args.header if args.header is not None else HEADER_DEFAULT
    with args.output.open("w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write("[functions]\n")
        f.write("extra = [\n")
        for t in sorted(targets):
            f.write(f"    0x{t:06X},\n")
        f.write("]\n")

    print(f"gen_disasm_seeds: {len(targets)} unique JSR/BSR targets -> {args.output}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
