#!/usr/bin/env python3
"""
gen_disasm_subs.py — extract every named subroutine entry from the
s1disasm listing and emit them as game.cfg `extra_func` directives.

Reads:   _s1disasm/sonic.lst
         segagenesisrecomp/tests/fixtures/sonic1/l1/code_addresses.txt
Writes:  segagenesisrecomp/sonicthehedgehog/sonic1.disasm_subs.txt

The strategy of this whole project is "the disasm is the ground truth
for what's a subroutine; the cfg is the coverage gap our discoverer
hasn't closed yet." This tool extracts every disasm-labeled entry
that looks like a real subroutine (proper name, code at that address)
and emits them all as seeds. As function_finder gets smarter at
discovering them automatically, individual entries here can be
removed and the corresponding behavior verified.

Filtering:
  KEEP  — capitalized labels: `Shi_Shield`, `VBlank_Paused`, `Sonic_Move`
  SKIP  — `loc_<hex>` / `locret_<hex>` (interior branch targets)
  SKIP  — `.foo` (leading-dot local labels, e.g. `.loop`, `.end`)
  SKIP  — `j_<hex>` (compiler-generated thunks if any)
  SKIP  — addresses that aren't code per the L1 fixture
  SKIP  — addresses already in game.cfg or sonic1.disasm_seeds.txt
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT     = Path(__file__).resolve().parents[5]
SUBMODULE_ROOT = Path(__file__).resolve().parents[2]

LST_PATH       = REPO_ROOT / "_s1disasm" / "sonic.lst"
CODE_ADDR_PATH = SUBMODULE_ROOT / "tests" / "fixtures" / "sonic1" / "l1" / "code_addresses.txt"
GAME_CFG       = SUBMODULE_ROOT / "sonicthehedgehog" / "game.cfg"
DISASM_SEEDS   = SUBMODULE_ROOT / "sonicthehedgehog" / "sonic1.disasm_seeds.txt"
OUT_PATH       = SUBMODULE_ROOT / "sonicthehedgehog" / "sonic1.disasm_subs.txt"

# A LABEL: line in the listing. Could appear as a standalone line or
# inline with code; in either case we capture the (address, name).
LBL_RE = re.compile(
    r"^(?:\(\d+\))?\s*\d+/\s+([0-9A-Fa-f]+)\s*:\s+([A-Za-z_.][\w.]*):"
)

# Names we intentionally exclude.
INTERIOR_NAME_RE = re.compile(
    r"^("
    r"loc_[0-9A-Fa-f]+|"
    r"locret_[0-9A-Fa-f]+|"
    r"j_[0-9A-Fa-f]+|"
    r"sub_[0-9A-Fa-f]+|"   # disasm sometimes uses sub_HEX for unnamed JSR targets
    r"byte_[0-9A-Fa-f]+|word_[0-9A-Fa-f]+|off_[0-9A-Fa-f]+|"
    r"\..*"                # any leading-dot local label
    r")$",
    re.IGNORECASE,
)

def load_addrs(path: Path, *, is_cfg: bool) -> set[int]:
    """Parse extra_func entries (with or without 0x prefix) from a cfg
    or seed file."""
    if not path.exists():
        return set()
    out: set[int] = set()
    pat = (re.compile(r"^\s*extra_func\s+(?:0x)?([0-9A-Fa-f]+)\b")
           if is_cfg else
           re.compile(r"^\s*extra_func\s+([0-9A-Fa-f]+)\b"))
    for line in path.read_text(encoding="utf-8").splitlines():
        m = pat.match(line)
        if m:
            out.add(int(m.group(1), 16))
    return out

def main() -> int:
    if not LST_PATH.exists():
        print(f"missing: {LST_PATH}", file=sys.stderr); return 2
    if not CODE_ADDR_PATH.exists():
        print(f"missing: {CODE_ADDR_PATH} — run gen_l1_fixtures.py first",
              file=sys.stderr); return 2

    code_addrs: set[int] = set()
    for line in CODE_ADDR_PATH.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"): continue
        try: code_addrs.add(int(line, 16))
        except ValueError: pass

    already = load_addrs(GAME_CFG, is_cfg=True) | load_addrs(DISASM_SEEDS, is_cfg=False)

    # First pass: collect every (addr, name) label in the listing.
    addr_names: dict[int, list[str]] = {}
    skipped_interior = 0
    for line in LST_PATH.read_text(encoding="utf-8", errors="replace").splitlines():
        m = LBL_RE.match(line)
        if not m: continue
        try: a = int(m.group(1), 16)
        except ValueError: continue
        name = m.group(2)
        if INTERIOR_NAME_RE.match(name):
            skipped_interior += 1
            continue
        addr_names.setdefault(a, []).append(name)

    candidates = sorted(addr_names)

    # Filter: must be code, not already seeded.
    keep: list[tuple[int, str]] = []
    skipped_data    = 0
    skipped_existing = 0
    for a in candidates:
        if a not in code_addrs:
            skipped_data += 1; continue
        if a in already:
            skipped_existing += 1; continue
        keep.append((a, "/".join(addr_names[a])))

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUT_PATH.open("w", encoding="utf-8", newline="\n") as f:
        f.write(
            "# sonic1.disasm_subs.txt — auto-generated by\n"
            "# tests/tools/gen_disasm_subs.py.\n"
            "#\n"
            "# Every disasm-labeled subroutine entry that's NOT already\n"
            "# discovered by function_finder, NOT already in game.cfg, and\n"
            "# NOT already in sonic1.disasm_seeds.txt. The cfg becomes a\n"
            "# measurable coverage gap; as discovery improves this file\n"
            "# can shrink.\n"
            "#\n"
            "# Loaded via game.cfg's extra_func_file directive.\n"
            "\n"
        )
        for a, name in keep:
            f.write(f"extra_func {a:06X}   # {name}\n")

    print(
        f"gen_disasm_subs: {len(keep)} subroutines emitted -> {OUT_PATH}\n"
        f"  candidates: {len(candidates)}\n"
        f"  skipped: interior-name={skipped_interior}, "
        f"data-not-code={skipped_data}, already-seeded={skipped_existing}"
    )
    return 0

if __name__ == "__main__":
    sys.exit(main())
