#!/usr/bin/env python3
"""
gen_disasm_jumptables.py — extract PC-indexed jump tables from an AS .lst
listing. Emits game.cfg-compatible `jump_table <start> <end> <stride> <fmt>`
directives plus `extra_func <target>` for every reachable entry.

Reads:   <disasm>/<game>.lst
         segagenesisrecomp/tests/fixtures/<game>/l1/code_addresses.txt
Writes:  segagenesisrecomp/<game>/<prefix>.disasm_jumptables.txt

The recompiler discovers PC-indexed JMPs by scanning instructions, but
without static enumeration it cannot follow them past the dispatch site.
Each "unresolved" PC-indexed jump table is a discovery hole. Disasms
encode jump tables as one of two shapes; we extract both:

    PCREL_W :  <Base>:
                   dc.w  Target_0 - <Base>
                   dc.w  Target_1 - <Base>
                   ...

    ABS_L   :  <Base>:
                   dc.l  Target_0
                   dc.l  Target_1
                   ...

Detection walks the listing row-by-row. A run becomes a jump table when
2+ consecutive entries at consecutive addresses (stride 2 for PCREL_W,
stride 4 for ABS_L) all resolve to in-ROM, even, code addresses (per the
L1 code_addresses fixture). Each emitted directive carries the start,
end (exclusive), stride and format — the recompiler honors these
verbatim, no additional inference required.

The strict code-address filter is what separates jump tables from the
many other dc.l/dc.w runs in a disasm (sprite mappings, art/PLC
pointers, level layouts, palette tables). Data tables fail validation
because their targets land in non-code regions or address 0.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT      = Path(__file__).resolve().parents[5]
SUBMODULE_ROOT = Path(__file__).resolve().parents[2]

LST_PATH       = REPO_ROOT / "_s1disasm" / "sonic.lst"
CODE_ADDR_PATH = SUBMODULE_ROOT / "tests" / "fixtures" / "sonic1" / "l1" / "code_addresses.txt"
OUT_PATH       = SUBMODULE_ROOT / "sonicthehedgehog" / "sonic1.disasm_jumptables.txt"

HEADER_DEFAULT = (
    "# {prefix}.disasm_jumptables.txt — auto-generated by\n"
    "# tests/tools/gen_disasm_jumptables.py.\n"
    "#\n"
    "# Every PC-indexed jump table found by walking the disasm .lst.\n"
    "# Each table emits a `jump_table` directive plus `extra_func`\n"
    "# entries for each enumerated target. Loaded via game.cfg's\n"
    "# `jump_table_file` directive.\n"
    "#\n"
    "# Format:\n"
    "#   jump_table <start_hex> <end_hex_exclusive> <stride> <abs|pcrel16>\n"
    "#   extra_func <target_hex>     # <label>\n"
    "\n"
)

# Match a primary listing row:
#   "[ (1) ]   LINE_NO/  ADDR : REST"
# Only rows that actually emit (or label) at an address concern us.
LINE_RE = re.compile(
    r"^(?:\(\d+\)\s+)?\s*\d+/\s+([0-9A-Fa-f]+)\s*:\s*(.*)$"
)

# Source patterns we recognize as jump-table entries. The optional
# leading "Label:" (or "Label1:Label2:...") covers tables whose base
# label is pinned inline with the first entry, e.g.
#   VBlank_Index: dc.w VBlank_Lag-VBlank_Index
PCREL_W_RE = re.compile(
    r"^\s*(?:[A-Za-z_][\w.]*\s*:\s*)*"
    r"dc\.w\s+([A-Za-z_.][\w.]*)\s*-\s*([A-Za-z_.][\w.]*)\s*(?:;.*)?$"
)
ABS_L_RE = re.compile(
    r"^\s*(?:[A-Za-z_][\w.]*\s*:\s*)*"
    r"dc\.l\s+([A-Za-z_.][\w.]*)\s*(?:;.*)?$"
)

# Labels pinned to the current address. AS produces several forms in
# the listing depending on how the label was declared:
#   - "Name:"                       — standard, may be inline before code
#   - "Name label *"                — AS pseudo-op, also pins to *
#   - "name := target"              — alias, may need indirection
# Equate marker rows look like "=$NNNN     <label-form> ...", so we
# match anywhere in the source rather than anchoring to the start.
LABEL_INLINE_RE = re.compile(
    r"(?<![\w.])([A-Za-z_][\w.]*)\s*:(?!=)"
)
LABEL_DECL_RE = re.compile(
    r"(?<![\w.])([A-Za-z_][\w.]*)\s+label\s+\*"
)
ALIAS_RE = re.compile(
    r"(?<![\w.])([A-Za-z_][\w.]*)\s*:=\s*([A-Za-z_][\w.]*)"
)


def parse_emit_row(rest: str):
    """
    Given the post-':' portion of a listing row, return
    (bytes_hex_list, source_text) when the row emits bytes, else
    (None, source_text). Macro and equate marker rows return
    (None, rest).
    """
    if not rest:
        return None, ""
    # Macro/equate markers don't emit a fresh byte run we want.
    if rest.startswith("(MACRO") or rest.startswith("="):
        return None, rest
    # Consume leading 4-char hex tokens. Stop on first non-hex token.
    tokens = rest.split()
    bytes_hex: list[str] = []
    for t in tokens:
        if re.fullmatch(r"[0-9A-Fa-f]{4}", t):
            bytes_hex.append(t)
        else:
            break
    if not bytes_hex:
        return None, rest
    # Source begins after the byte tokens. Locate by re-finding the
    # joined run in the original string so we preserve formatting.
    consumed = " ".join(bytes_hex)
    idx = rest.index(consumed) + len(consumed)
    return bytes_hex, rest[idx:].lstrip()


def load_code_addrs(path: Path) -> set[int]:
    out: set[int] = set()
    if not path.exists():
        return out
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            out.add(int(line, 16))
        except ValueError:
            pass
    return out


def signed_w(b_hi: int, b_lo: int) -> int:
    v = (b_hi << 8) | b_lo
    return v - 0x10000 if v & 0x8000 else v


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lst", type=Path, default=LST_PATH,
                    help="AS .lst listing produced by the disasm build")
    ap.add_argument("--code-addrs", type=Path, default=CODE_ADDR_PATH,
                    help="code_addresses.txt fixture (from gen_l1_fixtures.py)")
    ap.add_argument("-o", "--output", type=Path, default=OUT_PATH,
                    help="output .disasm_jumptables.txt")
    ap.add_argument("--prefix", type=str, default="sonic1",
                    help="cfg output_prefix; appears in the file header")
    ap.add_argument("--rom-max", type=lambda s: int(s, 0), default=0x400000,
                    help="reject targets >= this address (default 0x400000)")
    ap.add_argument("--header", type=str, default=None,
                    help="override the file's header comment")
    ap.add_argument("--min-entries", type=int, default=2,
                    help="minimum entries to qualify as a jump table")
    args = ap.parse_args()

    if not args.lst.exists():
        print(f"missing: {args.lst}", file=sys.stderr); return 2
    if not args.code_addrs.exists():
        print(f"missing: {args.code_addrs} — run gen_l1_fixtures.py first",
              file=sys.stderr); return 2

    code_addrs = load_code_addrs(args.code_addrs)
    if not code_addrs:
        print(f"empty: {args.code_addrs}", file=sys.stderr); return 2

    # ----- Pass 1: collect all labels, aliases, and emit rows ----------
    label_addr: dict[str, int] = {}
    aliases:    dict[str, str] = {}
    rows: list[tuple[int, list[str] | None, str]] = []  # (addr, bytes_or_none, source)

    for raw in args.lst.read_text(encoding="utf-8", errors="replace").splitlines():
        m = LINE_RE.match(raw)
        if not m:
            continue
        try:
            addr = int(m.group(1), 16)
        except ValueError:
            continue
        rest = m.group(2)
        bytes_hex, source = parse_emit_row(rest)

        # Capture every label form anywhere in the row. AS prints
        # equate markers as "=$NNNN  Name label *" / "=$NNNN  alias :=
        # target", so anchored matches miss them — we search instead.
        for mm in LABEL_INLINE_RE.finditer(rest):
            label_addr.setdefault(mm.group(1), addr)
        for mm in LABEL_DECL_RE.finditer(rest):
            label_addr.setdefault(mm.group(1), addr)
        for mm in ALIAS_RE.finditer(rest):
            aliases.setdefault(mm.group(1), mm.group(2))
            label_addr.setdefault(mm.group(1), addr)

        if bytes_hex is not None:
            rows.append((addr, bytes_hex, source))

    # Resolve transitive aliases (a := b, b := c -> a -> c's addr).
    for name, target in list(aliases.items()):
        seen: set[str] = {name}
        cur = target
        while cur in aliases and cur not in seen:
            seen.add(cur)
            cur = aliases[cur]
        if cur in label_addr:
            label_addr[name] = label_addr[cur]

    # ----- Pass 2: walk emitted rows looking for table runs ------------
    # Sort rows by address (stable) — rows already arrive in source
    # order which is monotonic in addr for code/data segments.
    # Build address -> row index for quick lookup.
    by_idx_addr: dict[int, int] = {}
    for i, (a, _, _) in enumerate(rows):
        # Multiple rows can share an address (macro line + emit line);
        # keep the first emit-row only. parse_emit_row already filtered
        # out non-emit rows, but a macro can still produce multiple
        # consecutive emits at the same addr from chained directives.
        # Use the first hit so subsequent walks find a clean stride.
        by_idx_addr.setdefault(a, i)

    pcrel_tables: list[dict] = []
    abs_tables: list[dict] = []
    used_rows: set[int] = set()

    for i, (addr, bytes_hex, source) in enumerate(rows):
        if i in used_rows:
            continue

        # Try PCREL_W first. The base label often resolves to a macro
        # variable that AS reassigns dozens of times across the listing
        # (e.g., "current_offset_table"), so we don't trust label_addr
        # for it. Instead we treat the first row's address as the
        # table base — by disasm convention the offset-table label is
        # pinned to the first entry, so target = first_addr + offset.
        m = PCREL_W_RE.match(source)
        if m and len(bytes_hex) == 1:
            base = m.group(2)
            base_addr = addr
            entries: list[tuple[int, str]] = []
            row_idxs: list[int] = []
            cur = i
            expected_addr = addr
            while cur < len(rows):
                a2, b2, s2 = rows[cur]
                if a2 != expected_addr:
                    break
                mm = PCREL_W_RE.match(s2)
                if not mm or len(b2) != 1 or mm.group(2) != base:
                    break
                word = int(b2[0], 16)
                off = word - 0x10000 if word & 0x8000 else word
                target = (base_addr + off) & 0xFFFFFF
                if (target & 1) or target >= args.rom_max:
                    break
                if target not in code_addrs:
                    break
                entries.append((target, mm.group(1)))
                row_idxs.append(cur)
                expected_addr += 2
                cur += 1

            if len(entries) >= args.min_entries:
                pcrel_tables.append({
                    "start": addr,
                    "end":   addr + 2 * len(entries),
                    "stride": 2,
                    "format": "pcrel16",
                    "base":  base,
                    "base_addr": base_addr,
                    "entries": entries,
                })
                used_rows.update(row_idxs)
                continue

        # Then ABS_L
        m2 = ABS_L_RE.match(source)
        if m2 and len(bytes_hex) == 2:
            entries = []
            row_idxs = []
            cur = i
            expected_addr = addr
            while cur < len(rows):
                a2, b2, s2 = rows[cur]
                if a2 != expected_addr:
                    break
                mm = ABS_L_RE.match(s2)
                if not mm or len(b2) != 2:
                    break
                target = ((int(b2[0], 16) << 16) | int(b2[1], 16)) & 0xFFFFFF
                if (target & 1) or target >= args.rom_max:
                    break
                if target not in code_addrs:
                    break
                entries.append((target, mm.group(1)))
                row_idxs.append(cur)
                expected_addr += 4
                cur += 1

            if len(entries) >= args.min_entries:
                abs_tables.append({
                    "start": addr,
                    "end":   addr + 4 * len(entries),
                    "stride": 4,
                    "format": "abs",
                    "entries": entries,
                })
                used_rows.update(row_idxs)
                continue

    # ----- Emit ---------------------------------------------------------
    args.output.parent.mkdir(parents=True, exist_ok=True)
    header = (args.header if args.header is not None
              else HEADER_DEFAULT.format(prefix=args.prefix))

    pcrel_tables.sort(key=lambda t: t["start"])
    abs_tables.sort(key=lambda t: t["start"])

    targets: set[int] = set()
    target_names: dict[int, str] = {}
    for t in pcrel_tables + abs_tables:
        for addr_t, name in t["entries"]:
            targets.add(addr_t)
            target_names.setdefault(addr_t, name)

    with args.output.open("w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write(f"# Tables found: {len(pcrel_tables)} pcrel16, {len(abs_tables)} abs\n")
        f.write(f"# Unique targets: {len(targets)}\n\n")

        if pcrel_tables:
            f.write("# ---- PCREL_W tables ----\n")
            for t in pcrel_tables:
                f.write(f"jump_table {t['start']:06X} {t['end']:06X} 2 pcrel16"
                        f"   # {t['base']} ({len(t['entries'])} entries)\n")
            f.write("\n")
        if abs_tables:
            f.write("# ---- ABS_L tables ----\n")
            for t in abs_tables:
                first_name = t["entries"][0][1] if t["entries"] else ""
                f.write(f"jump_table {t['start']:06X} {t['end']:06X} 4 abs"
                        f"   # {len(t['entries'])} entries, first={first_name}\n")
            f.write("\n")

        f.write("# ---- Targets ----\n")
        for a in sorted(targets):
            f.write(f"extra_func {a:06X}   # {target_names[a]}\n")

    print(
        f"gen_disasm_jumptables: {len(pcrel_tables)} pcrel16 + "
        f"{len(abs_tables)} abs tables, {len(targets)} unique targets -> {args.output}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
