#!/usr/bin/env python3
"""
gen_disasm_subs.py — extract every named subroutine entry from the
s1disasm listing and emit them as a TOML discovery file's
[functions].extra array.

Reads:   _s1disasm/sonic.lst
         segagenesisrecomp/tests/fixtures/sonic1/l1/code_addresses.txt
Writes:  segagenesisrecomp/sonicthehedgehog/sonic1.disasm_subs.toml

The strategy of this whole project is "the disasm is the ground truth
for what's a subroutine; the cfg is the coverage gap our discoverer
hasn't closed yet." This tool extracts every disasm-labeled entry
that looks like a real subroutine (proper name, code at that address)
and emits them all as seeds. As function_finder gets smarter at
discovering them automatically, individual entries here can be
removed and the corresponding behavior verified.

Filtering:
  KEEP  — capitalized labels: `Shi_Shield`, `VBlank_Paused`, `Sonic_Move`
  SKIP  — `loc_<hex>` / `locret_<hex>` (interior branch targets)
  SKIP  — `.foo` (leading-dot local labels, e.g. `.loop`, `.end`)
  SKIP  — `j_<hex>` (compiler-generated thunks if any)
  SKIP  — addresses that aren't code per the L1 fixture
  SKIP  — addresses already in game.cfg or sonic1.disasm_seeds.txt
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO_ROOT     = Path(__file__).resolve().parents[5]
SUBMODULE_ROOT = Path(__file__).resolve().parents[2]

LST_PATH       = REPO_ROOT / "_s1disasm" / "sonic.lst"
CODE_ADDR_PATH = SUBMODULE_ROOT / "tests" / "fixtures" / "sonic1" / "l1" / "code_addresses.txt"
GAME_CFG       = SUBMODULE_ROOT / "sonicthehedgehog" / "game.toml"
DISASM_SEEDS   = SUBMODULE_ROOT / "sonicthehedgehog" / "sonic1.disasm_seeds.toml"
OUT_PATH       = SUBMODULE_ROOT / "sonicthehedgehog" / "sonic1.disasm_subs.toml"
HEADER_DEFAULT = (
    "# sonic1.disasm_subs.toml — auto-generated by\n"
    "# tests/tools/gen_disasm_subs.py.\n"
    "#\n"
    "# Every disasm-labeled subroutine entry that's NOT already\n"
    "# discovered by function_finder, NOT already in game.toml, and\n"
    "# NOT already in sonic1.disasm_seeds.toml. The list becomes a\n"
    "# measurable coverage gap; as discovery improves this file\n"
    "# can shrink. Reference from game.toml:\n"
    "#   [game]\n"
    "#   discovery_files = [\"sonic1.disasm_subs.toml\"]\n"
    "\n"
)

# A LABEL: line in the listing. Could appear as a standalone line or
# inline with code; in either case we capture the (address, name).
LBL_RE = re.compile(
    r"^(?:\(\d+\))?\s*\d+/\s+([0-9A-Fa-f]+)\s*:\s+([A-Za-z_.][\w.]*):"
)

# Names we intentionally exclude.
INTERIOR_NAME_RE = re.compile(
    r"^("
    r"loc_[0-9A-Fa-f]+|"
    r"locret_[0-9A-Fa-f]+|"
    r"j_[0-9A-Fa-f]+|"
    r"sub_[0-9A-Fa-f]+|"   # disasm sometimes uses sub_HEX for unnamed JSR targets
    r"byte_[0-9A-Fa-f]+|word_[0-9A-Fa-f]+|off_[0-9A-Fa-f]+|"
    r"\..*"                # any leading-dot local label
    r")$",
    re.IGNORECASE,
)

def load_addrs(path: Path, *, is_cfg: bool) -> set[int]:
    """Parse hex addresses from a TOML discovery file. Accepts a flat
    [functions].extra integer array (TOML hex literals like 0xNNNNNN).
    The is_cfg arg is preserved for argparse-call compatibility but
    no longer affects parsing — both inputs are TOML now.
    """
    del is_cfg
    if not path.exists():
        return set()
    out: set[int] = set()
    try:
        try:
            import tomllib  # py3.11+
        except ImportError:
            import tomli as tomllib  # py<3.11 fallback
        with path.open("rb") as f:
            doc = tomllib.load(f)
    except Exception:
        return out
    fns = doc.get("functions") or {}
    for v in fns.get("extra") or []:
        try: out.add(int(v))
        except (TypeError, ValueError): pass
    return out

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--lst", type=Path, default=LST_PATH,
                    help="AS .lst listing produced by the disasm build")
    ap.add_argument("--code-addrs", type=Path, default=CODE_ADDR_PATH,
                    help="code_addresses.txt fixture (from gen_l1_fixtures.py)")
    ap.add_argument("--game-cfg", type=Path, default=GAME_CFG,
                    help="game.cfg to dedupe against (its extra_func entries are skipped)")
    ap.add_argument("--disasm-seeds", type=Path, default=DISASM_SEEDS,
                    help="disasm_seeds.txt to dedupe against")
    ap.add_argument("-o", "--output", type=Path, default=OUT_PATH,
                    help="output .disasm_subs.txt")
    ap.add_argument("--header", type=str, default=None,
                    help="override the file's header comment")
    args = ap.parse_args()

    if not args.lst.exists():
        print(f"missing: {args.lst}", file=sys.stderr); return 2
    if not args.code_addrs.exists():
        print(f"missing: {args.code_addrs} — run gen_l1_fixtures.py first",
              file=sys.stderr); return 2

    code_addrs: set[int] = set()
    for line in args.code_addrs.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"): continue
        try: code_addrs.add(int(line, 16))
        except ValueError: pass

    already = load_addrs(args.game_cfg, is_cfg=True) | load_addrs(args.disasm_seeds, is_cfg=False)

    # First pass: collect every (addr, name) label in the listing.
    addr_names: dict[int, list[str]] = {}
    skipped_interior = 0
    for line in args.lst.read_text(encoding="utf-8", errors="replace").splitlines():
        m = LBL_RE.match(line)
        if not m: continue
        try: a = int(m.group(1), 16)
        except ValueError: continue
        name = m.group(2)
        if INTERIOR_NAME_RE.match(name):
            skipped_interior += 1
            continue
        addr_names.setdefault(a, []).append(name)

    candidates = sorted(addr_names)

    # Filter: must be code, not already seeded.
    keep: list[tuple[int, str]] = []
    skipped_data    = 0
    skipped_existing = 0
    for a in candidates:
        if a not in code_addrs:
            skipped_data += 1; continue
        if a in already:
            skipped_existing += 1; continue
        keep.append((a, "/".join(addr_names[a])))

    args.output.parent.mkdir(parents=True, exist_ok=True)
    header = args.header if args.header is not None else HEADER_DEFAULT
    with args.output.open("w", encoding="utf-8", newline="\n") as f:
        f.write(header)
        f.write("[functions]\n")
        f.write("extra = [\n")
        for a, name in keep:
            f.write(f"    0x{a:06X},   # {name}\n")
        f.write("]\n")

    print(
        f"gen_disasm_subs: {len(keep)} subroutines emitted -> {args.output}\n"
        f"  candidates: {len(candidates)}\n"
        f"  skipped: interior-name={skipped_interior}, "
        f"data-not-code={skipped_data}, already-seeded={skipped_existing}"
    )
    return 0

if __name__ == "__main__":
    sys.exit(main())
