/*
 * game_config.c — TOML-only game config loader.
 *
 * The legacy whitespace-separated `.cfg` format has been retired. All
 * game projects now use `game.toml`, parsed by tomlc99 (see toml.h).
 * The schema mirrors what nesrecomp ships:
 *
 *     [game]
 *     output_prefix      = "sonic2"
 *     annotations        = "annotations_from_disasm.csv"
 *     vblank_yield_addr  = 0x002998        # optional
 *     allow_68020_branch = false
 *     jump_table_autodiscovery = false
 *     discovery_files    = ["sonic2.discovery.toml"]   # merged in
 *
 *     [functions]
 *     extra     = [0x000206, 0x000408, 0x000F54]
 *     blacklist = []
 *
 *     [[jump_table]]
 *     start  = 0x000468
 *     end    = 0x000484
 *     stride = 2
 *     format = "pcrel16"          # or "abs"
 *
 *     [[protected_range]]
 *     lo = 0x010000
 *     hi = 0x010040
 *
 * Discovery files (auto-generated by gen_disasm_labels.py /
 * gen_disasm_jumptables.py / etc.) are themselves TOML and are merged
 * into the parent config — only their `[functions].extra`,
 * `[functions].blacklist`, `[[jump_table]]`, and `[[protected_range]]`
 * arrays contribute. A discovery file's `[game]` table is ignored.
 */
#include "game_config.h"
#include "toml.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* ------------------------------------------------------------------ */
/* Dynamic-array growth (unchanged from the cfg era).                 */

static void *grow_to_fit(void *arr, int *cap_ptr, int count, size_t elem_size) {
    if (count < *cap_ptr) return arr;
    int new_cap = *cap_ptr ? *cap_ptr * 2 : 64;
    while (new_cap <= count) new_cap *= 2;
    void *p = realloc(arr, (size_t)new_cap * elem_size);
    if (!p) {
        fprintf(stderr, "game_config: out of memory growing to %d entries\n", new_cap);
        abort();
    }
    *cap_ptr = new_cap;
    return p;
}

static void append_extra_func(GameConfig *cfg, uint32_t addr) {
    cfg->extra_funcs = grow_to_fit(cfg->extra_funcs,
                                   &cfg->extra_func_cap,
                                   cfg->extra_func_count,
                                   sizeof(uint32_t));
    cfg->extra_funcs[cfg->extra_func_count++] = addr;
}

static void append_blacklist(GameConfig *cfg, uint32_t addr) {
    cfg->blacklist = grow_to_fit(cfg->blacklist,
                                 &cfg->blacklist_cap,
                                 cfg->blacklist_count,
                                 sizeof(uint32_t));
    cfg->blacklist[cfg->blacklist_count++] = addr;
}

static void append_protected_range(GameConfig *cfg, uint32_t lo, uint32_t hi) {
    cfg->protected_ranges = grow_to_fit(cfg->protected_ranges,
                                        &cfg->protected_range_cap,
                                        cfg->protected_range_count,
                                        sizeof(ProtectedRange));
    int idx = cfg->protected_range_count++;
    cfg->protected_ranges[idx].lo = lo;
    cfg->protected_ranges[idx].hi = hi;
}

static void append_jump_table(GameConfig *cfg, uint32_t start, uint32_t end,
                              uint32_t stride, JumpTableFormat fmt) {
    cfg->jump_tables = grow_to_fit(cfg->jump_tables,
                                   &cfg->jump_table_cap,
                                   cfg->jump_table_count,
                                   sizeof(JumpTableEntry));
    JumpTableEntry *e = &cfg->jump_tables[cfg->jump_table_count++];
    e->start_addr   = start;
    e->end_addr     = end;
    e->stride_bytes = stride ? stride : 4;
    e->format       = fmt;
}

/* Resolve a relative path against a base file's directory. */
static void resolve_path(const char *base, const char *rel, char *out, int out_size) {
    const char *slash  = strrchr(base, '/');
    const char *bslash = strrchr(base, '\\');
    const char *sep    = slash > bslash ? slash : bslash;
    if (sep) {
        int dir_len = (int)(sep - base) + 1;
        snprintf(out, out_size, "%.*s%s", dir_len, base, rel);
    } else {
        strncpy(out, rel, out_size - 1);
        out[out_size - 1] = '\0';
    }
}

/* ------------------------------------------------------------------ */
/* tomlc99 read helpers.                                              */

static bool toml_string_into(toml_table_t *tbl, const char *key,
                             char *dst, size_t dst_size)
{
    toml_datum_t d = toml_string_in(tbl, key);
    if (!d.ok) return false;
    strncpy(dst, d.u.s, dst_size - 1);
    dst[dst_size - 1] = '\0';
    free(d.u.s);
    return true;
}

static bool toml_bool_or(toml_table_t *tbl, const char *key, bool def) {
    toml_datum_t d = toml_bool_in(tbl, key);
    return d.ok ? (bool)d.u.b : def;
}

static uint32_t toml_u32_or(toml_table_t *tbl, const char *key, uint32_t def) {
    toml_datum_t d = toml_int_in(tbl, key);
    return d.ok ? (uint32_t)d.u.i : def;
}

static JumpTableFormat parse_jt_format(const char *s) {
    /* Accepts "pcrel16" / "pcrel_w" → PCREL_W; everything else → ABS_L. */
    if (s && (strcmp(s, "pcrel16") == 0 || strcmp(s, "pcrel_w") == 0))
        return JT_FMT_PCREL_W;
    return JT_FMT_ABS_L;
}

/* ------------------------------------------------------------------ */
/* Discovery-file merge: pulls in [functions].extra, [functions].blacklist,
 * [[jump_table]], [[protected_range]] from a child TOML. The child's
 * [game] section is ignored — discovery is data, not policy. */

static bool merge_toml(GameConfig *cfg, toml_table_t *root, const char *src_path);

static bool load_and_merge_toml(GameConfig *cfg, const char *path) {
    FILE *f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "[GameConfig] cannot open '%s'\n", path);
        return false;
    }
    char errbuf[256];
    toml_table_t *root = toml_parse_file(f, errbuf, sizeof(errbuf));
    fclose(f);
    if (!root) {
        fprintf(stderr, "[GameConfig] TOML parse error in '%s': %s\n", path, errbuf);
        return false;
    }
    bool ok = merge_toml(cfg, root, path);
    toml_free(root);
    return ok;
}

static bool merge_toml(GameConfig *cfg, toml_table_t *root, const char *src_path) {
    /* [functions].extra (array of ints) */
    toml_table_t *funcs = toml_table_in(root, "functions");
    if (funcs) {
        toml_array_t *extra = toml_array_in(funcs, "extra");
        if (extra) {
            int n = toml_array_nelem(extra);
            for (int i = 0; i < n; i++) {
                toml_datum_t d = toml_int_at(extra, i);
                if (d.ok) append_extra_func(cfg, (uint32_t)d.u.i);
            }
        }
        toml_array_t *bl = toml_array_in(funcs, "blacklist");
        if (bl) {
            int n = toml_array_nelem(bl);
            for (int i = 0; i < n; i++) {
                toml_datum_t d = toml_int_at(bl, i);
                if (d.ok) append_blacklist(cfg, (uint32_t)d.u.i);
            }
        }
    }

    /* [[jump_table]] */
    toml_array_t *jts = toml_array_in(root, "jump_table");
    if (jts) {
        int n = toml_array_nelem(jts);
        for (int i = 0; i < n; i++) {
            toml_table_t *t = toml_table_at(jts, i);
            if (!t) continue;
            uint32_t start  = toml_u32_or(t, "start",  0);
            uint32_t end    = toml_u32_or(t, "end",    0);
            uint32_t stride = toml_u32_or(t, "stride", 4);
            char fmt[32] = {0};
            toml_string_into(t, "format", fmt, sizeof(fmt));
            append_jump_table(cfg, start, end, stride, parse_jt_format(fmt));
        }
    }

    /* [[protected_range]] */
    toml_array_t *pr = toml_array_in(root, "protected_range");
    if (pr) {
        int n = toml_array_nelem(pr);
        for (int i = 0; i < n; i++) {
            toml_table_t *t = toml_table_at(pr, i);
            if (!t) continue;
            uint32_t lo = toml_u32_or(t, "lo", 0);
            uint32_t hi = toml_u32_or(t, "hi", 0);
            append_protected_range(cfg, lo, hi);
            printf("[GameConfig] Protected range: $%06X-$%06X (from %s)\n",
                   lo, hi, src_path ? src_path : "<root>");
        }
    }

    return true;
}

/* ------------------------------------------------------------------ */

void game_config_init_empty(GameConfig *cfg) {
    memset(cfg, 0, sizeof(*cfg));
}

void game_config_free(GameConfig *cfg) {
    free(cfg->jump_tables);
    free(cfg->extra_funcs);
    free(cfg->blacklist);
    free(cfg->protected_ranges);
    memset(cfg, 0, sizeof(*cfg));
}

bool game_config_load(GameConfig *cfg, const char *path) {
    /* Reject the legacy .cfg path with a clear migration message. */
    size_t plen = strlen(path);
    if (plen >= 4 && strcmp(path + plen - 4, ".cfg") == 0) {
        fprintf(stderr,
            "[GameConfig] '%s' is the legacy .cfg format which has been "
            "retired. Pass the new game.toml instead. See tools/migrate_cfg.py "
            "or the migration plan for details.\n", path);
        return false;
    }

    game_config_init_empty(cfg);

    FILE *f = fopen(path, "r");
    if (!f) {
        fprintf(stderr, "[GameConfig] cannot open '%s'\n", path);
        return false;
    }
    char errbuf[256];
    toml_table_t *root = toml_parse_file(f, errbuf, sizeof(errbuf));
    fclose(f);
    if (!root) {
        fprintf(stderr, "[GameConfig] TOML parse error in '%s': %s\n", path, errbuf);
        return false;
    }

    /* [game] — scalars + discovery_files */
    toml_table_t *game = toml_table_in(root, "game");
    if (game) {
        toml_string_into(game, "output_prefix",
                         cfg->output_prefix, sizeof(cfg->output_prefix));
        toml_string_into(game, "annotations",
                         cfg->annotations_path, sizeof(cfg->annotations_path));
        cfg->vblank_yield_addr        = toml_u32_or(game, "vblank_yield_addr", 0);
        cfg->allow_68020_branch       = toml_bool_or(game, "allow_68020_branch", false);
        cfg->jump_table_autodiscovery = toml_bool_or(game, "jump_table_autodiscovery", false);

        /* discovery_files: array of relative TOML paths to merge in. */
        toml_array_t *df = toml_array_in(game, "discovery_files");
        if (df) {
            int n = toml_array_nelem(df);
            for (int i = 0; i < n; i++) {
                toml_datum_t d = toml_string_at(df, i);
                if (!d.ok) continue;
                char child_path[512];
                resolve_path(path, d.u.s, child_path, sizeof(child_path));
                int before_funcs = cfg->extra_func_count;
                int before_jt    = cfg->jump_table_count;
                if (load_and_merge_toml(cfg, child_path)) {
                    fprintf(stderr,
                        "[GameConfig] merged '%s': +%d extra_funcs, +%d jump_tables\n",
                        child_path,
                        cfg->extra_func_count - before_funcs,
                        cfg->jump_table_count  - before_jt);
                }
                free(d.u.s);
            }
        }
    }

    /* Inline [functions] / [[jump_table]] / [[protected_range]] from
     * the root document — same merge function as the discovery files. */
    bool ok = merge_toml(cfg, root, path);
    toml_free(root);

    if (cfg->blacklist_count > 0)
        printf("[GameConfig] %d blacklisted addresses loaded\n", cfg->blacklist_count);

    return ok;
}

bool game_config_is_blacklisted(const GameConfig *cfg, uint32_t addr) {
    for (int i = 0; i < cfg->blacklist_count; i++)
        if (cfg->blacklist[i] == addr)
            return true;
    return false;
}

bool game_config_is_protected(const GameConfig *cfg, uint32_t addr) {
    for (int i = 0; i < cfg->protected_range_count; i++)
        if (addr >= cfg->protected_ranges[i].lo && addr <= cfg->protected_ranges[i].hi)
            return true;
    return false;
}
