# Writes genesis_build_info.h: the human-readable half of a runner build's
# identity (the exact half is the executable fingerprint computed at run
# time, runner/runtime_evidence.c). Run in script mode, once at configure
# time and again before every build of the executable:
#
#   cmake -DOUT=<header> -DENGINE_DIR=<engine checkout> -DGAME_DIR=<game repo>
#         [-DGIT=<git executable>] [-DGAME_VERSION=<project version>]
#         -P GenesisBuildInfo.cmake
#
# The header is rewritten only when its content changes, so only the one
# translation unit that includes it recompiles after a commit.

foreach(_v OUT ENGINE_DIR GAME_DIR)
    if(NOT DEFINED ${_v})
        message(FATAL_ERROR "GenesisBuildInfo.cmake: ${_v} is required")
    endif()
endforeach()

function(_genesis_git_describe out dir)
    set(_d "unknown")
    if(GIT AND EXISTS "${dir}")
        execute_process(
            COMMAND "${GIT}" -C "${dir}" describe --always --dirty --abbrev=10
            OUTPUT_VARIABLE _o RESULT_VARIABLE _r
            OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
        if(_r EQUAL 0 AND NOT _o STREQUAL "")
            set(_d "${_o}")
        endif()
    endif()
    string(REPLACE "\"" "" _d "${_d}")
    set(${out} "${_d}" PARENT_SCOPE)
endfunction()

_genesis_git_describe(_engine "${ENGINE_DIR}")
_genesis_git_describe(_game "${GAME_DIR}")
if(NOT DEFINED GAME_VERSION OR GAME_VERSION STREQUAL "")
    set(GAME_VERSION "dev")
endif()
string(REPLACE "\"" "" GAME_VERSION "${GAME_VERSION}")

set(_content
"/* Generated by cmake/GenesisBuildInfo.cmake. Do not edit. */
#define GENESIS_BUILD_ENGINE_GIT \"${_engine}\"
#define GENESIS_BUILD_GAME_GIT \"${_game}\"
#define GENESIS_BUILD_GAME_VERSION \"${GAME_VERSION}\"
")

set(_old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" _old)
endif()
if(NOT _old STREQUAL _content)
    file(WRITE "${OUT}" "${_content}")
endif()
